export type ToolCategory = 'map' | 'viz' | 'ai' | 'data' | 'space' | 'util' | '3d' | 'media' | 'crypto' | 'dev';
export type LoadType = 'script' | 'css' | 'api_endpoint';

export interface ToolDef { id: string; name: string; desc?: string; category: ToolCategory; url: string; type: LoadType; globalVar?: string; }

export const FALLBACK_TOOLS: ToolDef[] = [
  // --- 1. الخرائط (20) ---
  { id: 'leaflet', name: 'Leaflet', category: 'map', url: 'https://unpkg.com/leaflet@1.9.4/dist/leaflet.js', type: 'script', globalVar: 'L' },
  { id: 'mapbox', name: 'Mapbox GL', category: 'map', url: 'https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.js', type: 'script', globalVar: 'mapboxgl' },
  { id: 'openlayers', name: 'OpenLayers', category: 'map', url: 'https://cdn.jsdelivr.net/npm/ol@v8.1.0/dist/ol.js', type: 'script', globalVar: 'ol' },
  { id: 'cesium', name: 'Cesium', category: 'map', url: 'https://cesium.com/downloads/cesiumjs/releases/1.110/Build/Cesium/Cesium.js', type: 'script', globalVar: 'Cesium' },
  { id: 'turf', name: 'Turf', category: 'map', url: 'https://cdn.jsdelivr.net/npm/@turf/turf/turf.min.js', type: 'script', globalVar: 'turf' },
  { id: 'deckgl', name: 'Deck.gl', category: 'map', url: 'https://unpkg.com/deck.gl@latest/dist.min.js', type: 'script', globalVar: 'deck' },
  { id: 'esri', name: 'Esri Leaflet', category: 'map', url: 'https://unpkg.com/esri-leaflet@3.0.10/dist/esri-leaflet.js', type: 'script', globalVar: 'L.esri' },
  { id: 'stamen', name: 'Stamen', category: 'map', url: 'https://stamen-maps.a.ssl.fastly.net/js/tile.stamen.js', type: 'script' },
  { id: 'proj4', name: 'Proj4', category: 'map', url: 'https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.9.0/proj4.js', type: 'script', globalVar: 'proj4' },
  { id: 'geobuf', name: 'Geobuf', category: 'map', url: 'https://unpkg.com/geobuf/dist/geobuf.js', type: 'script', globalVar: 'geobuf' },
  { id: 'leaflet-heat', name: 'Leaflet Heat', category: 'map', url: 'https://leaflet.github.io/Leaflet.heat/dist/leaflet-heat.js', type: 'script' },
  { id: 'leaflet-draw', name: 'Leaflet Draw', category: 'map', url: 'https://cdnjs.cloudflare.com/ajax/libs/leaflet.draw/1.0.4/leaflet.draw.js', type: 'script' },
  { id: 'leaflet-cluster', name: 'MarkerCluster', category: 'map', url: 'https://unpkg.com/leaflet.markercluster@1.4.1/dist/leaflet.markercluster.js', type: 'script' },
  { id: 'maplibre', name: 'MapLibre', category: 'map', url: 'https://unpkg.com/maplibre-gl@3.6.2/dist/maplibre-gl.js', type: 'script', globalVar: 'maplibregl' },
  { id: 'h3', name: 'H3-js', category: 'map', url: 'https://unpkg.com/h3-js', type: 'script', globalVar: 'h3' },
  { id: 'topojson', name: 'TopoJSON', category: 'map', url: 'https://unpkg.com/topojson@3', type: 'script', globalVar: 'topojson' },
  { id: 'osmtogeojson', name: 'OSM to GeoJSON', category: 'map', url: 'https://unpkg.com/osmtogeojson@3.0.0/osmtogeojson.js', type: 'script', globalVar: 'osmtogeojson' },
  { id: 'polylabel', name: 'Polylabel', category: 'map', url: 'https://unpkg.com/polylabel@1.1.0/polylabel.js', type: 'script', globalVar: 'polylabel' },
  { id: 'rbush', name: 'RBush', category: 'map', url: 'https://unpkg.com/rbush@3.0.1/rbush.min.js', type: 'script', globalVar: 'rbush' },
  { id: 'cheap-ruler', name: 'Cheap Ruler', category: 'map', url: 'https://unpkg.com/cheap-ruler@3.0.2/cheap-ruler.min.js', type: 'script', globalVar: 'cheapRuler' },

  // --- 2. الذكاء (AI) (20) ---
  { id: 'tfjs', name: 'TensorFlow', category: 'ai', url: 'https://cdn.jsdelivr.net/npm/@tensorflow/tfjs', type: 'script', globalVar: 'tf' },
  { id: 'mobilenet', name: 'MobileNet', category: 'ai', url: 'https://cdn.jsdelivr.net/npm/@tensorflow-models/mobilenet', type: 'script', globalVar: 'mobilenet' },
  { id: 'webllm', name: 'WebLLM', category: 'ai', url: 'https://cdn.jsdelivr.net/npm/@mlc-ai/web-llm', type: 'script', globalVar: 'webllm' },
  { id: 'brain', name: 'Brain.js', category: 'ai', url: 'https://unpkg.com/brain.js', type: 'script', globalVar: 'brain' },
  { id: 'faceapi', name: 'Face API', category: 'ai', url: 'https://cdn.jsdelivr.net/npm/face-api.js', type: 'script', globalVar: 'faceapi' },
  { id: 'ml5', name: 'ML5', category: 'ai', url: 'https://unpkg.com/ml5@latest/dist/ml5.min.js', type: 'script', globalVar: 'ml5' },
  { id: 'onnx', name: 'ONNX', category: 'ai', url: 'https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.min.js', type: 'script', globalVar: 'ort' },
  { id: 'tesseract', name: 'Tesseract', category: 'ai', url: 'https://cdn.jsdelivr.net/npm/tesseract.js@2.1.0/dist/tesseract.min.js', type: 'script', globalVar: 'Tesseract' },
  { id: 'natural', name: 'Natural', category: 'ai', url: 'https://cdn.jsdelivr.net/npm/natural', type: 'script' },
  { id: 'compromise', name: 'Compromise', category: 'ai', url: 'https://unpkg.com/compromise', type: 'script', globalVar: 'nlp' },
  { id: 'sentiment', name: 'Sentiment', category: 'ai', url: 'https://unpkg.com/sentiment', type: 'script', globalVar: 'Sentiment' },
  { id: 'franc', name: 'Franc', category: 'ai', url: 'https://unpkg.com/franc@6', type: 'script', globalVar: 'franc' },
  { id: 'retext', name: 'Retext', category: 'ai', url: 'https://unpkg.com/retext', type: 'script', globalVar: 'retext' },
  { id: 'svm', name: 'SVM.js', category: 'ai', url: 'https://unpkg.com/svm', type: 'script', globalVar: 'svm' },
  { id: 'decision-tree', name: 'Decision Tree', category: 'ai', url: 'https://unpkg.com/decision-tree', type: 'script', globalVar: 'dt' },
  { id: 'mind-ar', name: 'MindAR', category: 'ai', url: 'https://cdn.jsdelivr.net/npm/mind-ar@1.2.0/dist/mindar-image.prod.js', type: 'script', globalVar: 'MindAR' },
  { id: 'tracking', name: 'Tracking.js', category: 'ai', url: 'https://trackingjs.com/bower/tracking.js', type: 'script', globalVar: 'tracking' },
  { id: 'clmtrackr', name: 'Clmtrackr', category: 'ai', url: 'https://www.auduno.com/clmtrackr/clmtrackr.js', type: 'script', globalVar: 'clm' },
  { id: 'pico', name: 'Pico.js', category: 'ai', url: 'https://unpkg.com/picojs', type: 'script', globalVar: 'pico' },
  { id: 'handtrack', name: 'HandTrack', category: 'ai', url: 'https://cdn.jsdelivr.net/npm/handtrackjs/dist/handtrack.min.js', type: 'script', globalVar: 'handTrack' },

  // --- 3. الرسوم (Viz) (20) ---
  { id: 'd3', name: 'D3.js', category: 'viz', url: 'https://d3js.org/d3.v7.min.js', type: 'script', globalVar: 'd3' },
  { id: 'chartjs', name: 'Chart.js', category: 'viz', url: 'https://cdn.jsdelivr.net/npm/chart.js', type: 'script', globalVar: 'Chart' },
  { id: 'recharts', name: 'Recharts', category: 'viz', url: 'https://unpkg.com/recharts/umd/Recharts.js', type: 'script', globalVar: 'Recharts' },
  { id: 'plotly', name: 'Plotly', category: 'viz', url: 'https://cdn.plot.ly/plotly-2.24.1.min.js', type: 'script', globalVar: 'Plotly' },
  { id: 'echarts', name: 'ECharts', category: 'viz', url: 'https://cdn.jsdelivr.net/npm/echarts/dist/echarts.min.js', type: 'script', globalVar: 'echarts' },
  { id: 'apex', name: 'ApexCharts', category: 'viz', url: 'https://cdn.jsdelivr.net/npm/apexcharts', type: 'script', globalVar: 'ApexCharts' },
  { id: 'billboard', name: 'Billboard', category: 'viz', url: 'https://cdn.jsdelivr.net/npm/billboard.js/dist/billboard.min.js', type: 'script', globalVar: 'bb' },
  { id: 'frappe', name: 'Frappe', category: 'viz', url: 'https://cdn.jsdelivr.net/npm/frappe-charts@1.2.4/dist/frappe-charts.min.iife.js', type: 'script', globalVar: 'frappe' },
  { id: 'toast', name: 'Toast UI', category: 'viz', url: 'https://uicdn.toast.com/chart/latest/toastui-chart.min.js', type: 'script', globalVar: 'toastui' },
  { id: 'chartist', name: 'Chartist', category: 'viz', url: 'https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js', type: 'script', globalVar: 'Chartist' },
  { id: 'morris', name: 'Morris', category: 'viz', url: 'https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js', type: 'script', globalVar: 'Morris' },
  { id: 'peity', name: 'Peity', category: 'viz', url: 'https://cdnjs.cloudflare.com/ajax/libs/peity/3.3.0/jquery.peity.min.js', type: 'script' },
  { id: 'sparkline', name: 'Sparkline', category: 'viz', url: 'https://cdnjs.cloudflare.com/ajax/libs/jquery-sparklines/2.1.2/jquery.sparkline.min.js', type: 'script' },
  { id: 'sigma', name: 'Sigma', category: 'viz', url: 'https://cdnjs.cloudflare.com/ajax/libs/sigma.js/1.2.1/sigma.min.js', type: 'script', globalVar: 'sigma' },
  { id: 'cytoscape', name: 'Cytoscape', category: 'viz', url: 'https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.23.0/cytoscape.min.js', type: 'script', globalVar: 'cytoscape' },
  { id: 'vis', name: 'Vis.js', category: 'viz', url: 'https://unpkg.com/vis-network/standalone/umd/vis-network.min.js', type: 'script', globalVar: 'vis' },
  { id: 'fabric', name: 'Fabric', category: 'viz', url: 'https://cdnjs.cloudflare.com/ajax/libs/fabric.js/5.3.1/fabric.min.js', type: 'script', globalVar: 'fabric' },
  { id: 'konva', name: 'Konva', category: 'viz', url: 'https://unpkg.com/konva@9.2.0/konva.min.js', type: 'script', globalVar: 'Konva' },
  { id: 'p5', name: 'P5.js', category: 'viz', url: 'https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js', type: 'script', globalVar: 'p5' },
  { id: 'paper', name: 'Paper.js', category: 'viz', url: 'https://cdnjs.cloudflare.com/ajax/libs/paper.js/0.12.17/paper-full.min.js', type: 'script', globalVar: 'paper' },

  // --- 4. ثلاثي الأبعاد (3D) (15) ---
  { id: 'three', name: 'Three.js', category: '3d', url: 'https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js', type: 'script', globalVar: 'THREE' },
  { id: 'babylon', name: 'Babylon', category: '3d', url: 'https://cdn.babylonjs.com/babylon.js', type: 'script', globalVar: 'BABYLON' },
  { id: 'aframe', name: 'A-Frame', category: '3d', url: 'https://aframe.io/releases/1.4.0/aframe.min.js', type: 'script', globalVar: 'AFRAME' },
  { id: 'ar', name: 'AR.js', category: '3d', url: 'https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js', type: 'script' },
  { id: 'model', name: 'ModelViewer', category: '3d', url: 'https://ajax.googleapis.com/ajax/libs/model-viewer/3.1.1/model-viewer.min.js', type: 'script' },
  { id: 'zdog', name: 'Zdog', category: '3d', url: 'https://unpkg.com/zdog@1/dist/zdog.dist.min.js', type: 'script', globalVar: 'Zdog' },
  { id: 'matter', name: 'Matter', category: '3d', url: 'https://cdnjs.cloudflare.com/ajax/libs/matter-js/0.19.0/matter.min.js', type: 'script', globalVar: 'Matter' },
  { id: 'cannon', name: 'Cannon', category: '3d', url: 'https://cdnjs.cloudflare.com/ajax/libs/cannon.js/0.6.2/cannon.min.js', type: 'script', globalVar: 'CANNON' },
  { id: 'oimo', name: 'Oimo', category: '3d', url: 'https://cdnjs.cloudflare.com/ajax/libs/oimo/1.0.9/oimo.min.js', type: 'script', globalVar: 'OIMO' },
  { id: 'ammo', name: 'Ammo', category: '3d', url: 'https://github.com/kripken/ammo.js/raw/master/builds/ammo.js', type: 'script', globalVar: 'Ammo' },
  { id: 'regl', name: 'Regl', category: '3d', url: 'https://cdnjs.cloudflare.com/ajax/libs/regl/2.1.0/regl.min.js', type: 'script', globalVar: 'createRegl' },
  { id: 'ogl', name: 'OGL', category: '3d', url: 'https://unpkg.com/ogl', type: 'script' },
  { id: 'twgl', name: 'TWGL', category: '3d', url: 'https://twgljs.org/dist/4.x/twgl-full.min.js', type: 'script', globalVar: 'twgl' },
  { id: 'pixi', name: 'Pixi', category: '3d', url: 'https://cdnjs.cloudflare.com/ajax/libs/pixi.js/7.2.4/pixi.min.js', type: 'script', globalVar: 'PIXI' },
  { id: 'phaser', name: 'Phaser', category: '3d', url: 'https://cdn.jsdelivr.net/npm/phaser@3.60.0/dist/phaser.min.js', type: 'script', globalVar: 'Phaser' },

  // --- 5. أدوات مساعدة (Util) (30) ---
  { id: 'lodash', name: 'Lodash', category: 'util', url: 'https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js', type: 'script', globalVar: '_' },
  { id: 'moment', name: 'Moment', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js', type: 'script', globalVar: 'moment' },
  { id: 'axios', name: 'Axios', category: 'util', url: 'https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js', type: 'script', globalVar: 'axios' },
  { id: 'socket', name: 'Socket.IO', category: 'util', url: 'https://cdn.socket.io/4.5.4/socket.io.min.js', type: 'script', globalVar: 'io' },
  { id: 'uuid', name: 'UUID', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/uuid/8.3.2/uuid.min.js', type: 'script', globalVar: 'uuid' },
  { id: 'crypto', name: 'CryptoJS', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js', type: 'script', globalVar: 'CryptoJS' },
  { id: 'bcrypt', name: 'Bcrypt', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/bcryptjs/2.4.3/bcrypt.min.js', type: 'script', globalVar: 'dcodeIO' },
  { id: 'jsencrypt', name: 'JSEncrypt', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/jsencrypt/3.3.2/jsencrypt.min.js', type: 'script', globalVar: 'JSEncrypt' },
  { id: 'filesaver', name: 'FileSaver', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js', type: 'script', globalVar: 'saveAs' },
  { id: 'jszip', name: 'JSZip', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js', type: 'script', globalVar: 'JSZip' },
  { id: 'pdfmake', name: 'PDFMake', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js', type: 'script', globalVar: 'pdfMake' },
  { id: 'jspdf', name: 'jsPDF', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js', type: 'script', globalVar: 'jspdf' },
  { id: 'howler', name: 'Howler', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/howler/2.2.3/howler.min.js', type: 'script', globalVar: 'Howl' },
  { id: 'tone', name: 'Tone', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/tone/14.8.49/Tone.js', type: 'script', globalVar: 'Tone' },
  { id: 'anime', name: 'Anime', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js', type: 'script', globalVar: 'anime' },
  { id: 'gsap', name: 'GSAP', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js', type: 'script', globalVar: 'gsap' },
  { id: 'sweetalert', name: 'SweetAlert', category: 'util', url: 'https://cdn.jsdelivr.net/npm/sweetalert2@11', type: 'script', globalVar: 'Swal' },
  { id: 'tippy', name: 'Tippy', category: 'util', url: 'https://unpkg.com/tippy.js@6', type: 'script', globalVar: 'tippy' },
  { id: 'aos', name: 'AOS', category: 'util', url: 'https://unpkg.com/aos@2.3.1/dist/aos.js', type: 'script', globalVar: 'AOS' },
  { id: 'cleave', name: 'Cleave', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/cleave.js/1.6.0/cleave.min.js', type: 'script', globalVar: 'Cleave' },
  { id: 'flatpickr', name: 'Flatpickr', category: 'util', url: 'https://cdn.jsdelivr.net/npm/flatpickr', type: 'script', globalVar: 'flatpickr' },
  { id: 'driver', name: 'Driver', category: 'util', url: 'https://cdn.jsdelivr.net/npm/driver.js/dist/driver.min.js', type: 'script', globalVar: 'Driver' },
  { id: 'localforage', name: 'LocalForage', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/localforage/1.10.0/localforage.min.js', type: 'script', globalVar: 'localforage' },
  { id: 'lz', name: 'LZ-String', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/lz-string/1.4.4/lz-string.min.js', type: 'script', globalVar: 'LZString' },
  { id: 'showdown', name: 'Showdown', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/showdown/2.1.0/showdown.min.js', type: 'script', globalVar: 'showdown' },
  { id: 'highlight', name: 'Highlight', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js', type: 'script', globalVar: 'hljs' },
  { id: 'clipboard', name: 'Clipboard', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.11/clipboard.min.js', type: 'script', globalVar: 'ClipboardJS' },
  { id: 'hotkeys', name: 'Hotkeys', category: 'util', url: 'https://unpkg.com/hotkeys-js/dist/hotkeys.min.js', type: 'script', globalVar: 'hotkeys' },
  { id: 'screenfull', name: 'Screenfull', category: 'util', url: 'https://cdnjs.cloudflare.com/ajax/libs/screenfull.js/5.2.0/screenfull.min.js', type: 'script', globalVar: 'screenfull' },
  { id: 'ffmpeg', name: 'FFmpeg', category: 'util', url: 'https://unpkg.com/@ffmpeg/ffmpeg@0.11.0/dist/ffmpeg.min.js', type: 'script', globalVar: 'FFmpeg' },

  // --- 6. مصادر البيانات (APIs) (95) ---
  { id: 'om', name: 'Open-Meteo', category: 'data', url: 'https://api.open-meteo.com/v1/forecast', type: 'api_endpoint' },
  { id: 'nasa-power', name: 'NASA POWER', category: 'data', url: 'https://power.larc.nasa.gov', type: 'api_endpoint' },
  { id: 'usgs', name: 'USGS Quakes', category: 'data', url: 'https://earthquake.usgs.gov', type: 'api_endpoint' },
  { id: 'nasa-eonet', name: 'NASA EONET', category: 'data', url: 'https://eonet.gsfc.nasa.gov', type: 'api_endpoint' },
  { id: 'rainviewer', name: 'RainViewer', category: 'data', url: 'https://api.rainviewer.com', type: 'api_endpoint' },
  { id: 'waqi', name: 'WAQI Air', category: 'data', url: 'https://api.waqi.info', type: 'api_endpoint' },
  { id: 'nasa-apod', name: 'NASA APOD', category: 'space', url: 'https://api.nasa.gov/planetary/apod', type: 'api_endpoint' },
  { id: 'spacex', name: 'SpaceX', category: 'space', url: 'https://api.spacexdata.com', type: 'api_endpoint' },
  { id: 'solar', name: 'NOAA Solar', category: 'space', url: 'https://services.swpc.noaa.gov', type: 'api_endpoint' },
  { id: 'gdacs', name: 'GDACS', category: 'data', url: 'https://www.gdacs.org', type: 'api_endpoint' },
  { id: 'carbon', name: 'Carbon', category: 'data', url: 'https://api.carbonintensity.org.uk', type: 'api_endpoint' },
  { id: 'openuv', name: 'OpenUV', category: 'data', url: 'https://api.openuv.io', type: 'api_endpoint' },
  { id: 'stormglass', name: 'StormGlass', category: 'data', url: 'https://api.stormglass.io', type: 'api_endpoint' },
  { id: 'newsapi', name: 'News API', category: 'data', url: 'https://newsapi.org', type: 'api_endpoint' },
  { id: 'poke', name: 'PokeAPI', category: 'data', url: 'https://pokeapi.co', type: 'api_endpoint' },
  { id: 'rest', name: 'Countries', category: 'data', url: 'https://restcountries.com', type: 'api_endpoint' },
  { id: 'coin', name: 'CoinDesk', category: 'data', url: 'https://api.coindesk.com', type: 'api_endpoint' },
  { id: 'catfact', name: 'Cat Fact', category: 'data', url: 'https://catfact.ninja/fact', type: 'api_endpoint' },
  { id: 'dog', name: 'Dog API', category: 'data', url: 'https://dog.ceo/api/breeds/image/random', type: 'api_endpoint' },
  { id: 'bored', name: 'Bored', category: 'data', url: 'https://www.boredapi.com/api/activity', type: 'api_endpoint' },
  { id: 'agify', name: 'Agify', category: 'data', url: 'https://api.agify.io', type: 'api_endpoint' },
  { id: 'genderize', name: 'Genderize', category: 'data', url: 'https://api.genderize.io', type: 'api_endpoint' },
  { id: 'nationalize', name: 'Nationalize', category: 'data', url: 'https://api.nationalize.io', type: 'api_endpoint' },
  { id: 'ipify', name: 'IPify', category: 'data', url: 'https://api.ipify.org', type: 'api_endpoint' },
  { id: 'jokes', name: 'Jokes', category: 'data', url: 'https://official-joke-api.appspot.com', type: 'api_endpoint' },
  { id: 'randomuser', name: 'User Gen', category: 'data', url: 'https://randomuser.me', type: 'api_endpoint' },
  { id: 'zippopotam', name: 'Zip Code', category: 'data', url: 'https://api.zippopotam.us', type: 'api_endpoint' },
  { id: 'univ', name: 'Universities', category: 'data', url: 'http://universities.hipolabs.com', type: 'api_endpoint' },
  { id: 'fda', name: 'FDA Food', category: 'data', url: 'https://api.fda.gov/food', type: 'api_endpoint' },
  { id: 'exchangerate', name: 'Exchange', category: 'data', url: 'https://api.exchangerate-api.com', type: 'api_endpoint' },
  // ... (يمكنك إضافة المزيد بسهولة الآن)
];
